CENSUS_API_KEY = "YOUR_CENSUS_API_KEY"

PROJECT_FOLDER = r"C:\Path\To\UrbanHeatEquity"

CITY_NAME = "Phoenix"
STATE_FIPS = "04"
COUNTY_FIPS = "013"

ACS_YEAR = "2024"

LANDSAT_DATE_RANGE = "2023-09-01/2023-09-30"
MAX_CLOUD_COVER = 10

NLCD_TCC_YEAR = "2023"

AGOL_FOLDER_NAME = "Urban Heat Equity Portfolio"
